dev fibers2
YACLib/YACLib pull request #103
Opened 2021-10-29 19:55 UTC by myannyax

2021-10-30 15:33 UTC, MBkkt requested changes
Correct comments.
Write at least some benchmark (or better copy it from other libraries).
Remove the boilerplate code and classes.

2021-10-30 15:33 UTC, MBkkt commented on src/coroutines/CMakeLists.txt
> +  # todo: pick based on a system
We write todo like this:
```suggestion
  # TODO(myannyax) Pick based on a system
```

2021-10-30 15:33 UTC, MBkkt commented on src/coroutines/context/asm/switch_context_x86_64.S
> +    // for trampoline
https://github.com/YACLib/YACLib/pull/104
Check this

2021-10-30 15:33 UTC, MBkkt commented on src/coroutines/context/execution_context.hpp
> +class ExecutionContext {
Why do you use so many same contexts?

2021-10-30 15:33 UTC, MBkkt commented on src/coroutines/context/setup_stack/setup_stack_x64.hpp
> +struct YaclibFiberMachineContext {
You should use 
`void* registers[YACLIB_CONTEXT_SIZE];`
And use `switch_context_x86_64.hpp` for addressing

2021-10-30 15:33 UTC, MBkkt commented on src/coroutines/coroutine_impl.cpp
> +void CoroutineImpl::Resume() {
everywhere
```suggestion
}

void CoroutineImpl::Resume() {
```

2021-11-05 19:31 UTC, MBkkt requested changes

2021-11-05 19:31 UTC, MBkkt commented on test/unit/coroutines/basic.cpp
> +#include "yaclib/fibers/coroutine.hpp"
Use `#include <...>`

2021-11-05 19:31 UTC, MBkkt commented on .github/workflows/fibers.yml
> +          - {
Comment out windows and write todo

2021-11-05 19:31 UTC, MBkkt commented on include/yaclib/fibers/coroutine.hpp
> +#include "default_allocator.hpp"
Plz use `include <...>`

2021-11-05 19:31 UTC, MBkkt commented on include/yaclib/fibers/coroutine_base.hpp
> +#include "stack_view.hpp"
include <>

2021-11-05 19:31 UTC, MBkkt commented on include/yaclib/fibers/coroutine_base.hpp
> +    _context.Setup(stack_view, Trampoline, this);
Should be in cpp

2021-11-05 19:31 UTC, MBkkt commented on include/yaclib/fibers/detail/execution_context.hpp
> +#include "yaclib/fibers/stack_view.hpp"
include <>

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/CMakeLists.txt
> +  ${CMAKE_CURRENT_SOURCE_DIR}/context/asm/switch_context_x86_64.hpp
move to }/fiber/asm...

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/CMakeLists.txt
> +  ${YACLIB_INCLUDE_DIR}/fibers/detail/execution_context.hpp
fiber instead of fibers

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/context/default_allocator.cpp
> +DefaultAllocator default_allocator_instance;
Should be named gDefaultAllocator

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/context/execution_context.cpp
> +ExecutionContext::ExecutionContext() : _context(new void*[kAsmContextSize]) {
- [ ] Remove allocation.

Btw wrong size, you alloc 8*size, where size is count of registers * 8

Use char[kAsmContextSize]; and cast it to void**

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/context/setup_stack_x64.cpp
> +#include "setup_stack_x64.hpp"
include <>

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/context/setup_stack_x64.hpp
> +extern const size_t kAsmContextSize;
Use inline constexpr

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/context/setup_stack_x64.cpp
> +extern "C" void yaclib_trampoline();
Remove from namespace

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/context/setup_stack_x64.cpp
> +static const int kAlignment = 16;
constexpr

2021-11-05 19:31 UTC, MBkkt commented on src/fibers/coroutine.cpp
> +#include "yaclib/fibers/coroutine.hpp"
<>

2021-11-05 19:31 UTC, MBkkt commented on test/CMakeLists.txt
> +  unit/coroutines/basic
unit/fiber/basic

2021-11-06 12:27 UTC, myannyax commented on src/fibers/CMakeLists.txt
> +  ${CMAKE_CURRENT_SOURCE_DIR}/coroutine_base.cpp
CMAKE_CURRENT_SOURCE_DIR already contain fiber 🤔

2021-11-06 12:29 UTC, MBkkt commented on src/fibers/CMakeLists.txt
> +  ${CMAKE_CURRENT_SOURCE_DIR}/coroutine_base.cpp
Yeah

2021-11-07 09:56 UTC, MBkkt approved these changes

2021-11-10 18:21 UTC, MBkkt approved these changes

2021-11-10 18:22 UTC, merged