Minor fixes and refactoring
YACLib/YACLib pull request #119
Opened 2021-11-24 23:32 UTC by madoka-wizard

- Minor changes and code style fixes
- Implemented amazing testing system (see `WhenAny` tests)

Detailed description:
- Add branch coverage to lcov report
- Update .clang-tidy rules to avoid stupid warnings
- Fix stupid GCC warning
- Make style_guide more comprehensive
- Add MBkkt's TODO
- Implement ranged `Wait`/`WaitFor`/`WaitUntil` for iterators
- Fix Wait tests and update test/CMakeLists.txt
- Update `WhenAny` implementation
- Make ultimate `WhenAny` tests using cartesian product of different params
- Add `InlineCore`
- Separate `WhenAll` implementation from interface
- Code style fixes
- `WaitGroup` fixes

2021-12-11 19:54 UTC, MBkkt requested changes

2021-12-11 19:54 UTC, MBkkt commented on .github/workflows/test_coverage.yml
> +          lcov --rc lcov_branch_coverage=1 -d . -c                  -o lcov.info &&
Make two lcov.info one for codecov (without branch), one for us (with branch)

2021-12-11 19:54 UTC, MBkkt commented on CMakeLists.txt
> +set(CMAKE_POSITION_INDEPENDENT_CODE ON) # TODO(MBkkt) Do we really need this?
I think we can remove this and LTO

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/algo/detail/wait_impl.hpp
> +    return (... & functor(cs));  // TODO(MBkkt) Maybe (functor(cs) & ...) is better
- [ ] Remove TODO

These are the same expressions, the only difference is in associativity, which doesn't matter here and is correct
(... & some) -- (somef1 & somef2) & somef3
(some & ...) -- somef1 & (somef2 & somef3)

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/algo/detail/wait_impl.hpp
> +    return true;
Please add test

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/algo/detail/when_any_impl.hpp
> +    return std::move(*it);
Add test with vector length one

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/algo/detail/when_all_impl.hpp
> +void WhenAllImpl(util::Ptr<AllCombinator<T, N>>& combinator, Future<T>&& head, Future<Ts>&&... tail) {
Add constexpr plz

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/algo/detail/when_any_impl.hpp
> +void WhenAnyImpl(AnyCombinatorPtr<T, P>& combinator, Future<T>&& head, Future<Ts>&&... tail) {
Add constexpr plz

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/algo/when_all.hpp
>    auto [future, combinator] = detail::AllCombinator<T>::Make(size);
Add for all WhenAll static_assert(p == WhenPolicy::FirstFail, "TODO(Ri7ay) Add other policy for WhenAll")

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/async/detail/wait_core.hpp
> +    return cv.wait_until(guard, timeout_time, [this] {
remove this diff

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/util/result.hpp
> +  using VariantT = std::variant<std::monostate, std::error_code, std::exception_ptr,
using ValueT = std::conditional_t<std::is_void_v<T>, detail::Unit, T>;

2021-12-11 19:54 UTC, MBkkt commented on include/yaclib/util/result.hpp
>      if (std::holds_alternative<std::monostate>(_result)) {
I think better if first
if (std::holds_alternative<ValueT>(_result)) {
}
then exception, then error, last empty

2021-12-11 19:54 UTC, MBkkt commented on src/algo/wait_group.cpp
> +void WaitGroup::Add(Future<void>&& f) {
Add test

2021-12-16 23:58 UTC, closed without merging

2021-12-16 23:58 UTC, kononovk commented
Merged this changes in #123