First simple CPU bounded static thread pool
YACLib/YACLib pull request #32
Opened 2021-07-18 07:49 UTC by kononovk

2021-07-18 08:04 UTC, MBkkt requested changes

2021-07-18 08:04 UTC, MBkkt commented on src/executor/thread_pool.cpp
>      // TODO(kononovk): #2 After call: сalling Execute() for all,
Remove todo

2021-07-18 08:04 UTC, MBkkt commented on src/executor/thread_pool.cpp
> +    ChangeState(Stopped);
Doesn't work

2021-07-18 08:04 UTC, MBkkt commented on src/executor/thread_pool.cpp
> +      thread_ptr->Join();
Use thread_factory from other pr

2021-07-18 08:04 UTC, MBkkt commented on src/executor/thread_pool.cpp
> +      auto thread_ptr = _threads.PopBack();
PopFront()

2021-07-18 08:04 UTC, MBkkt commented on src/executor/thread_pool.cpp
> +      _cv.notify_one();
WTF

2021-07-18 08:04 UTC, MBkkt commented on test/thread_pool.cpp
> +      executor::MakeThreadPool(factory, std::thread::hardware_concurrency(),
Make different function as in another pr

2021-07-18 08:04 UTC, MBkkt commented on test/thread_pool.cpp
> +  tp->Execute(CreateTask([&ready] {
MakeTask

2021-07-18 08:04 UTC, MBkkt commented on test/thread_pool.cpp
> +#include <cpu_time.hpp>
Why are tests so simple?

2021-07-18 08:06 UTC, MBkkt commented on src/executor/thread_pool.cpp
>    container::intrusive::List<ITask> _tasks;
Leak

2021-07-18 08:06 UTC, MBkkt commented on src/executor/thread_pool.cpp
> +      std::unique_lock lk{_m};
guard good name btw

2021-07-18 08:10 UTC, MBkkt commented on src/executor/thread_pool.cpp
>      };
current_thread_pool = nullptr

2021-07-18 08:12 UTC, MBkkt commented on src/executor/thread_pool.cpp
> +thread_local IThreadPool* current_thread_pool;
`tlCurrentThreadPool`/`tCurrentThreadPool`/`lCurrentThreadPool` thread local
`sCurrentThreadPool` static
`kCurrentThreadPool` constexpr/const static
`gCurrentThreadPool` global
What do you think?

2021-07-18 08:13 UTC, MBkkt commented on src/executor/thread_pool.cpp
> +                         std::enable_shared_from_this<ThreadPool> {
Why?

2021-07-19 07:19 UTC, MBkkt commented on include/yaclib/executor/thread_factory.hpp
> +IThreadFactoryPtr MakeThreadFactory();
NIT
this overload should be first

2021-07-19 08:01 UTC, MBkkt requested changes

2021-07-19 08:01 UTC, MBkkt commented on test/CMakeLists.txt
> +set(BENCHMARK_ENABLE_TESTING NO)
- [ ] in `if (NOT BENCHMARK_FOUND)`

2021-07-19 08:01 UTC, MBkkt commented on test/thread_pool.cpp
> +#include "util/cpu_time.hpp"
- [ ] Tests are not done

2021-07-19 08:01 UTC, MBkkt commented on test/thread_factory.cpp
> +GTEST_TEST(decorator, priority) {
Add TODO

2021-07-19 18:06 UTC, kononovk commented on test/thread_pool.cpp
> +#include <cpu_time.hpp>
I will create task with implementation better test coverage

2021-07-19 22:48 UTC, MBkkt approved these changes

2021-07-19 22:50 UTC, merged