Add When Any
YACLib/YACLib pull request #76
Opened 2021-09-08 14:02 UTC by Ri7ay

2021-09-08 15:30 UTC, kononovk commented on include/yaclib/async/when_any.hpp
> +      return;
It seems we can change this to one CAS and avoid invalidating the cache lines.

2021-09-08 15:30 UTC, kononovk commented on test/unit/async/when_any.cpp
> +
delete unused code

2021-09-08 15:30 UTC, kononovk commented on test/unit/async/when_any.cpp
> +}  // namespace
Add empty line to the end of file, check `.githooks` to do it automatically

2021-09-08 15:30 UTC, kononovk commented on include/yaclib/async/when_any.hpp
> +}  // namespace yaclib::async
Add empty line to the end of file, check `.githooks` directory to do it automatically

2021-09-08 15:39 UTC, kononovk commented on include/yaclib/async/when_any.hpp
> +  AnyCombinator(Promise<T> promise) : _done{false}, _promise{std::move(promise)} {
Make this constructor explicit

2021-09-08 15:49 UTC, MBkkt requested changes
Very useful pattern:
 Run async operation
 Run same operation, but different context, for example other database instance

 WhenAny(f1, f2).Then(...). ...

In this case, we need the first success, but not the first error. I mean any error is suitable for us, but if we return an error, it should be means that all futures have completed with an error.

2021-09-08 15:49 UTC, MBkkt commented on include/yaclib/async/when_any.hpp
> +#pragma once
Very useful pattern:
 Run async operation
 Run same operation, but different context, for example other database instance

 WhenAny(f1, f2).Then(...). ...

In this case, we need the first success, but not the first error. I mean any error is suitable for us, but if we return an error, it should be means that all futures have completed with an error.

2021-09-12 15:19 UTC, MBkkt commented on include/yaclib/async/when_any.hpp
> +  }
Should be private

2021-09-12 15:23 UTC, MBkkt requested changes

2021-09-12 15:23 UTC, MBkkt commented on include/yaclib/async/when_any.hpp
> +  explicit AnyCombinator(Promise<T> promise, size_t size = 0) : _size{size}, _promise{std::move(promise)} {
Should be private

2021-09-12 15:23 UTC, MBkkt commented on include/yaclib/async/when_any.hpp
> +  alignas(kCacheLineSize) std::atomic<bool> _ex_er{false};
ex_er is bad naming
Maybe _error?

2021-09-12 15:23 UTC, MBkkt commented on include/yaclib/async/when_any.hpp
> +enum class PolicyWhenAny { FirstError, LastError };
```suggestion
enum class PolicyWhenAny { FirstError, LastError, };
```

2021-09-12 15:23 UTC, MBkkt commented on include/yaclib/async/when_all.hpp
> +  detail::WhenAllImpl<sizeof...(Fs) + 1>(combinator, std::move(head), std::forward<Fs>(tail)...);
Plz add
c = nullptr

2021-09-12 15:29 UTC, MBkkt commented on include/yaclib/async/when_any.hpp
> +  }
Should be private

2021-09-12 15:29 UTC, MBkkt commented on include/yaclib/async/when_any.hpp
> +    } else if (_size.fetch_sub(1, std::memory_order_acq_rel) <= 1U) {
==?

2021-09-12 15:31 UTC, MBkkt commented on include/yaclib/async/when_any.hpp
> +template <PolicyWhenAny P, typename T, typename... Fs>
What about default policy?

2021-09-12 22:54 UTC, MBkkt approved these changes

2021-09-12 23:11 UTC, MBkkt approved these changes

2021-09-12 23:14 UTC, merged